# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

env:
  - KONG_VER={{ if index .Env "KONG_VER"  }}{{ .Env.KONG_VER }}{{ else }}0.0.0{{ end }}

before:
  hooks:
    - go install github.com/google/go-licenses@v1.6.0
    - make license-report

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    files:
      - README.md
      - LICENSE
      - NOTICE
      - component_licenses
    wrap_in_directory: true

dockers_v2:
  - images:
      - "ghcr.io/hanlaur/kong"
    tags:
      - "{{.Env.KONG_VER}}-oidcify-{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - "--pull"
    extra_files:
      - README.md
      - LICENSE
      - NOTICE
      - component_licenses
