name: Check PR Label

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-labels:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v5

    - name: Check PR labels
      uses: actions/github-script@v7
      with:
        script: |
          const labels = context.payload.pull_request.labels.map(label => label.name);
          const requiredLabels = ['breaking', 'fix', 'feature', 'chore'];
          const hasRequiredLabel = labels.some(label => requiredLabels.includes(label));

          if (!hasRequiredLabel) {
            core.setFailed(`Pull request must have one of the following labels: ${requiredLabels.join(', ')}`);
          }
