name: release

concurrency:
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract Go version from go.mod
        id: extract-go-version
        run: |
          GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "GO_VERSION=$GO_VERSION" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Extract Kong version from Dockerfile
        id: kong_version
        run: echo kong_version=$(grep -oP '(?<=FROM kong:)\d+\.\d+\.\d+' Dockerfile) >> $GITHUB_OUTPUT

      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "goreleaser_flags=--snapshot" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a  # v6.4.0
        with:
          distribution: goreleaser
          version: "~> v2"
          # Publishing of container image disabled for now using --skip docker
          args: release --skip docker --clean ${{ env.goreleaser_flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KONG_VER: ${{ steps.kong_version.outputs.kong_version }}
